# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AI-NeuralNet-Kohonen
version:      0.142
version_from: lib/AI/NeuralNet/Kohonen.pm
installdirs:  site
requires:
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
